"""init

Revision ID: 51b36c819d5f
Revises: 
Create Date: 2019-12-07 22:55:45.980654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51b36c819d5f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prize',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('logo', sa.String(length=128), nullable=True),
    sa.Column('description', sa.String(length=128), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prize'))
    )
    op.create_table('station',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_station'))
    )
    op.create_index(op.f('ix_station_name'), 'station', ['name'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user'))
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=False)
    op.create_table('token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('value', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['station_id'], ['station.id'], name=op.f('fk_token_station_id_station')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_token'))
    )
    op.create_table('usedtoken',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['token_id'], ['token.id'], name=op.f('fk_usedtoken_token_id_token')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_usedtoken_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_usedtoken'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usedtoken')
    op.drop_table('token')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_station_name'), table_name='station')
    op.drop_table('station')
    op.drop_table('prize')
    # ### end Alembic commands ###
